# Site settings
title: Jimmy Vinh
description: Website about Jimmy Vinh
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Jimmy Vinh
user_description: I am a senior chemical engineering student at Arizona State University, and I am doing 4+1 accelerated master's program in materials science. 
I previously interned at Intel as a process engineer. I currently work in business operations at Amkor. Please feel free to connect with me on Linkedin or contact me via email.
user_title: Business Operations at Amkor | Chemical Engineering Student at ASU
email: jvinh@asu.edu
linkedin_username: jimmyvinh
github_username:  jimmyvinh

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
